<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipios = [
            ['departamento_id' => 1	, 	 'nombre' =>' Guatemala'],
            ['departamento_id' => 1	, 	 'nombre' =>' Santa Catarina Pinula'],
            ['departamento_id' => 1	, 	 'nombre' =>' San José Pinula'],
            ['departamento_id' => 1	, 	 'nombre' =>' San José del Golfo'],
            ['departamento_id' => 1	, 	 'nombre' =>' Palencia'],
            ['departamento_id' => 1	, 	 'nombre' =>' Chinautla'],
            ['departamento_id' => 1	, 	 'nombre' =>' San Pedro Ayampuc'],
            ['departamento_id' => 1	, 	 'nombre' =>' Mixco'],
            ['departamento_id' => 1	, 	 'nombre' =>' San Pedro Sacatepéquez'],
            ['departamento_id' => 1	, 	 'nombre' =>' San Juan Sacatépequez'],
            ['departamento_id' => 1	, 	 'nombre' =>' San Raymundo'],
            ['departamento_id' => 1	, 	 'nombre' =>' Chuarrancho'],
            ['departamento_id' => 1	, 	 'nombre' =>' Fraijanes'],
            ['departamento_id' => 1	, 	 'nombre' =>' Amatitlán'],
            ['departamento_id' => 1	, 	 'nombre' =>' Villa Nueva'],
            ['departamento_id' => 1	, 	 'nombre' =>' Villa Canales'],
            ['departamento_id' => 1	, 	 'nombre' =>' Petapa'],
            ['departamento_id' => 2	, 	 'nombre' =>' Guastatoya'],
            ['departamento_id' => 2	, 	 'nombre' =>' Morazán'],
            ['departamento_id' => 2	, 	 'nombre' =>' San Agustín Acasaguastlán'],
            ['departamento_id' => 2	, 	 'nombre' =>' San Cristóbal Acasaguastlán'],
            ['departamento_id' => 2	, 	 'nombre' =>' El Jícaro'],
            ['departamento_id' => 2	, 	 'nombre' =>' Sansare'],
            ['departamento_id' => 2	, 	 'nombre' =>' Sanarate'],
            ['departamento_id' => 2	, 	 'nombre' =>' San Antonio La Paz'],
            ['departamento_id' => 3	, 	 'nombre' =>' Antigua Guatemala'],
            ['departamento_id' => 3	, 	 'nombre' =>' Jocotenango'],
            ['departamento_id' => 3	, 	 'nombre' =>' Pastores'],
            ['departamento_id' => 3	, 	 'nombre' =>' Sumpango'],
            ['departamento_id' => 3	, 	 'nombre' =>' Sto. Domingo Xenacoj'],
            ['departamento_id' => 3	, 	 'nombre' =>' Santiago Sacatepéquez'],
            ['departamento_id' => 3	, 	 'nombre' =>' San Bartolomé Millpas Altas'],
            ['departamento_id' => 3	, 	 'nombre' =>' San Lucas Sacatepéquez'],
            ['departamento_id' => 3	, 	 'nombre' =>' Santa Lucia Milpas Altas'],
            ['departamento_id' => 3	, 	 'nombre' =>' Magdalena Milpas Altas'],
            ['departamento_id' => 3	, 	 'nombre' =>' Santa María de Jesús'],
            ['departamento_id' => 3	, 	 'nombre' =>' Ciudad Vieja'],
            ['departamento_id' => 3	, 	 'nombre' =>' San Miguel Dueñas'],
            ['departamento_id' => 3	, 	 'nombre' =>' Alotenango'],
            ['departamento_id' => 3	, 	 'nombre' =>' San Antonio Aguas Calientes'],
            ['departamento_id' => 3	, 	 'nombre' =>' Santa Catarina Barahona'],
            ['departamento_id' => 4	, 	 'nombre' =>' Chimaltenango'],
            ['departamento_id' => 4	, 	 'nombre' =>' San José Poaquil'],
            ['departamento_id' => 4	, 	 'nombre' =>' San Martín Jilotepeque'],
            ['departamento_id' => 4	, 	 'nombre' =>' Comalapa'],
            ['departamento_id' => 4	, 	 'nombre' =>' Santa Apolonia'],
            ['departamento_id' => 4	, 	 'nombre' =>' Tecpán Guatemala'],
            ['departamento_id' => 4	, 	 'nombre' =>' Patzún'],
            ['departamento_id' => 4	, 	 'nombre' =>' Pochuta'],
            ['departamento_id' => 4	, 	 'nombre' =>' Patzicia'],
            ['departamento_id' => 4	, 	 'nombre' =>' Santa Cruz Balanyá'],
            ['departamento_id' => 4	, 	 'nombre' =>' Acatenango'],
            ['departamento_id' => 4	, 	 'nombre' =>' Yepocapa'],
            ['departamento_id' => 4	, 	 'nombre' =>' San Andrés Iztapa'],
            ['departamento_id' => 4	, 	 'nombre' =>' Parramos'],
            ['departamento_id' => 4	, 	 'nombre' =>' Zaragoza'],
            ['departamento_id' => 4	, 	 'nombre' =>' El Tejar'],
            ['departamento_id' => 5	, 	 'nombre' =>' Escuintla'],
            ['departamento_id' => 5	, 	 'nombre' =>' Santa Lucía Cotzumalguapa'],
            ['departamento_id' => 5	, 	 'nombre' =>' La Democracia'],
            ['departamento_id' => 5	, 	 'nombre' =>' Siquinalá'],
            ['departamento_id' => 5	, 	 'nombre' =>' Masagua'],
            ['departamento_id' => 5	, 	 'nombre' =>' Tiquisate'],
            ['departamento_id' => 5	, 	 'nombre' =>' La Gomera'],
            ['departamento_id' => 5	, 	 'nombre' =>' Guanagazapa'],
            ['departamento_id' => 5	, 	 'nombre' =>' San José'],
            ['departamento_id' => 5	, 	 'nombre' =>' Iztapa'],
            ['departamento_id' => 5	, 	 'nombre' =>' Palín'],
            ['departamento_id' => 5	, 	 'nombre' =>' San Vicente Pacaya'],
            ['departamento_id' => 5	, 	 'nombre' =>' Nueva Concepción'],
            ['departamento_id' => 6	, 	 'nombre' =>' Cuilapa'],
            ['departamento_id' => 6	, 	 'nombre' =>' Barberena'],
            ['departamento_id' => 6	, 	 'nombre' =>' Santa Rosa de Lima'],
            ['departamento_id' => 6	, 	 'nombre' =>' Casillas'],
            ['departamento_id' => 6	,    'nombre' =>' San Rafael Las Flores'],
            ['departamento_id' => 6	, 	 'nombre' =>' Oratorio'],
            ['departamento_id' => 6	, 	 'nombre' =>' San Juan Tecuaco'],
            ['departamento_id' => 6	, 	 'nombre' =>' Chiquimulilla'],
            ['departamento_id' => 6	, 	 'nombre' =>' Taxisco'],
            ['departamento_id' => 6	, 	 'nombre' =>' Santa María Ixhuatán'],
            ['departamento_id' => 6	, 	 'nombre' =>' Guazacapán'],
            ['departamento_id' => 6	, 	 'nombre' =>' Santa Cruz Naranjo'],
            ['departamento_id' => 6	, 	 'nombre' =>' Pueblo Nuevo Viñas'],
            ['departamento_id' => 6	, 	 'nombre' =>' Nueva Santa Rosa'],
            ['departamento_id' => 7	, 	 'nombre' =>' Sololá'],
            ['departamento_id' => 7	, 	 'nombre' =>' San José Chacayá'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa María Visitación'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa Lucía Utatlán'],
            ['departamento_id' => 7	, 	 'nombre' =>' Nahualá'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa Catarina Ixtahuacán'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa Clara La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' Concepción'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Andrés Semetabaj'],
            ['departamento_id' => 7	, 	 'nombre' =>' Panajachel'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa Catarina Palopó'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Antonio Palopó'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Lucas Tolimán'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santa Cruz La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Pablo La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Marcos La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Juan La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' San Pedro La Laguna'],
            ['departamento_id' => 7	, 	 'nombre' =>' Santiago Atitlán'],
            ['departamento_id' => 8	, 	 'nombre' =>' Totonicapán'],
            ['departamento_id' => 8	, 	 'nombre' =>' San Cristóbal Totonicapán'],
            ['departamento_id' => 8	, 	 'nombre' =>' San Francisco El Alto'],
            ['departamento_id' => 8	, 	 'nombre' =>' San Andrés Xecul'],
            ['departamento_id' => 8	, 	 'nombre' =>' Momostenango'],
            ['departamento_id' => 8	, 	 'nombre' =>' Santa María Chiquimula'],
            ['departamento_id' => 8	, 	 'nombre' =>' Santa Lucía La Reforma'],
            ['departamento_id' => 8	, 	 'nombre' =>' San Bartolo Aguas Calientes'],
            ['departamento_id' => 9	, 	 'nombre' =>' Quetzaltenango'],
            ['departamento_id' => 9	, 	 'nombre' =>' Salcajá'],
            ['departamento_id' => 9	, 	 'nombre' =>' Olintepeque'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Carlos Sija'],
            ['departamento_id' => 9	, 	 'nombre' =>' Sibilia'],
            ['departamento_id' => 9	, 	 'nombre' =>' Cabricán'],
            ['departamento_id' => 9	, 	 'nombre' =>' Cajolá'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Miguel Siguilá'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Juan Ostuncalco'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Mateo'],
            ['departamento_id' => 9	, 	 'nombre' =>' Concepción Chiquirichapa'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Martín Sacatepéquez'],
            ['departamento_id' => 9	, 	 'nombre' =>' Almolonga'],
            ['departamento_id' => 9	, 	 'nombre' =>' Cantel'],
            ['departamento_id' => 9	, 	 'nombre' =>' Huitán'],
            ['departamento_id' => 9	, 	 'nombre' =>' Zunil'],
            ['departamento_id' => 9	, 	 'nombre' =>' Colomba'],
            ['departamento_id' => 9	, 	 'nombre' =>' San Francisco La Unión'],
            ['departamento_id' => 9	, 	 'nombre' =>' El Palmar'],
            ['departamento_id' => 9	, 	 'nombre' =>' Coatepeque'],
            ['departamento_id' => 9	, 	 'nombre' =>' Génova'],
            ['departamento_id' => 9	, 	 'nombre' =>' Flores Costa Cuca'],
            ['departamento_id' => 9	, 	 'nombre' =>' La Esperanza'],
            ['departamento_id' => 9	, 	 'nombre' =>' Palestina de los Altos'],
            ['departamento_id' => 10,  'nombre' =>'Mazatenango'],
            ['departamento_id' => 10,  'nombre' =>'Cuyotenango'],
            ['departamento_id' => 10,  'nombre' =>'San Francisco Zapotitlán'],
            ['departamento_id' => 10,  'nombre' =>'San Bernardino'],
            ['departamento_id' => 10,  'nombre' =>'San José El ídolo'],
            ['departamento_id' => 10,  'nombre' =>'Santo Domingo Suchitepéquez'],
            ['departamento_id' => 10,  'nombre' =>'San Lorenzo'],
            ['departamento_id' => 10,  'nombre' =>'Samayac'],
            ['departamento_id' => 10,  'nombre' =>'San Pablo Jocopilas'],
            ['departamento_id' => 10,  'nombre' =>'San Antonio Suchitepéquez'],
            ['departamento_id' => 10,  'nombre' =>'San Miguel Panán'],
            ['departamento_id' => 10,  'nombre' =>'San Gabriel'],
            ['departamento_id' => 10,  'nombre' =>'Chicacao'],
            ['departamento_id' => 10,  'nombre' =>'Patulul'],
            ['departamento_id' => 10,  'nombre' =>'Santa Bárbara'],
            ['departamento_id' => 10,  'nombre' =>'San Juan Bautista'],
            ['departamento_id' => 10,  'nombre' =>'Santo Tomás La Unión'],
            ['departamento_id' => 10, 'nombre' =>'Zunilito'],
            ['departamento_id' => 10,  'nombre' =>'Pueblo Nuevo'],
            ['departamento_id' => 10,  'nombre' =>'Río Bravo'],
            ['departamento_id' => 11,  'nombre' =>'Retalhuleu'],
            ['departamento_id' => 11, 'nombre' =>'San Sebastián'],
            ['departamento_id' => 11,  'nombre' =>'Santa Cruz Muluá'],
            ['departamento_id' => 11,  'nombre' =>'San Martín Zapotitlán'],
            ['departamento_id' => 11,  'nombre' =>'San Felipe Retalhuleu'],
            ['departamento_id' => 11,  'nombre' =>'San Andrés Villa Seca'],
            ['departamento_id' => 11, 'nombre' =>'Champerico'],
            ['departamento_id' => 11,  'nombre' =>'Nuevo San Carlos'],
            ['departamento_id' => 11,  'nombre' =>'El Asintal'],
            ['departamento_id' => 12,  'nombre' =>'San Marcos'],
            ['departamento_id' => 12,  'nombre' =>'San Pedro Sacatepéquez'],
            ['departamento_id' => 12,  'nombre' =>'San Antonio Sacatepéquez'],
            ['departamento_id' => 12,  'nombre' =>'Comitancillo'],
            ['departamento_id' => 12,  'nombre' =>'San Miguel Ixtahuacán'],
            ['departamento_id' => 12,  'nombre' =>'Concepción Tutuapa'],
            ['departamento_id' => 12,  'nombre' =>'Tacaná'],
            ['departamento_id' => 12,  'nombre' =>'Sibinal'],
            ['departamento_id' => 12,  'nombre' =>'Tajumulco'],
            ['departamento_id' => 12,  'nombre' =>'Tejutla'],
            ['departamento_id' => 12,  'nombre' =>'San Rafael Pie de la Cuesta'],
            ['departamento_id' => 12,  'nombre' =>'Nuevo Progreso'],
            ['departamento_id' => 12, 'nombre' =>'El Tumbador'],
            ['departamento_id' => 12,  'nombre' =>'El Rodeo'],
            ['departamento_id' => 12, 'nombre' =>'Malacatán'],
            ['departamento_id' => 12, 'nombre' =>'Catarina'],
            ['departamento_id' => 12, 'nombre' =>'Ayutla'],
            ['departamento_id' => 12,  'nombre' =>'Ocós'],
            ['departamento_id' => 12, 'nombre' =>'San Pablo'],
            ['departamento_id' => 12,  'nombre' =>'El Quetzal'],
            ['departamento_id' => 12,  'nombre' =>'La Reforma'],
            ['departamento_id' => 12,  'nombre' =>'Pajapita'],
            ['departamento_id' => 12,  'nombre' =>'Ixchiguán'],
            ['departamento_id' => 12,  'nombre' =>'San José Ojetenam'],
            ['departamento_id' => 12,  'nombre' =>'San Cristóbal Cucho'],
            ['departamento_id' => 12,  'nombre' =>'Sipacapa'],
            ['departamento_id' => 12, 'nombre' =>'Esquipulas Palo Gordo'],
            ['departamento_id' => 12, 'nombre' =>'Río Blanco'],
            ['departamento_id' => 12,  'nombre' =>'San Lorenzo'],
            ['departamento_id' => 13,  'nombre' =>'Huehuetenango'],
            ['departamento_id' => 13,  'nombre' =>'Chiantla'],
            ['departamento_id' => 13, 'nombre' =>'Malacatancito'],
            ['departamento_id' => 13, 'nombre' =>'Cuilco'],
            ['departamento_id' => 13, 'nombre' =>'Nentón'],
            ['departamento_id' => 13, 'nombre' =>'San Pedro Necta'],
            ['departamento_id' => 13, 'nombre' =>'Jacaltenango'],
            ['departamento_id' => 13, 'nombre' =>'Soloma'],
            ['departamento_id' => 13, 'nombre' =>'San Idelfonso Ixtahuacán'],
            ['departamento_id' => 13, 'nombre' =>'Santa Bárbara'],
            ['departamento_id' => 13, 'nombre' =>'La Libertad'],
            ['departamento_id' => 13, 'nombre' =>'La Democracia'],
            ['departamento_id' => 13, 'nombre' =>'San Miguel Acatán'],
            ['departamento_id' => 13, 'nombre' =>'San Rafael La Indepencia'],
            ['departamento_id' => 13, 'nombre' =>'Todos Santos Cuchumatán'],
            ['departamento_id' => 13, 'nombre' =>'San Juan Atitán'],
            ['departamento_id' => 13, 'nombre' =>'Santa Eulalia'],
            ['departamento_id' => 13, 'nombre' =>'San Mateo Ixtatán'],
            ['departamento_id' => 13, 'nombre' =>'Colotenango'],
            ['departamento_id' => 13, 'nombre' =>'San Sebastián Huehuetenango'],
            ['departamento_id' => 13, 'nombre' =>'Tectitán'],
            ['departamento_id' => 13, 'nombre' =>'Concepción Huista'],
            ['departamento_id' => 13, 'nombre' =>'San Juan Ixcoy'],
            ['departamento_id' => 13, 'nombre' =>'San Antonio Huista'],
            ['departamento_id' => 13, 'nombre' =>'San Sebastián Coatán'],
            ['departamento_id' => 13, 'nombre' =>'Barillas'],
            ['departamento_id' => 13, 'nombre' =>'Aguacatán'],
            ['departamento_id' => 13, 'nombre' =>'San Rafael Pétzal'],
            ['departamento_id' => 13, 'nombre' =>'San Gaspar Ixchil'],
            ['departamento_id' => 13, 'nombre' =>'Santiago Chimaltenango'],
            ['departamento_id' => 13, 'nombre' =>'Santa Ana Huista'],
            ['departamento_id' => 14, 'nombre' =>'Santa Cruz del Quiché'],
            ['departamento_id' => 14, 'nombre' =>'Chiché'],
            ['departamento_id' => 14, 'nombre' =>'Chinique'],
            ['departamento_id' => 14, 'nombre' =>'Zacualpa'],
            ['departamento_id' => 14, 'nombre' =>'Chajul'],
            ['departamento_id' => 14, 'nombre' =>'Chichicastenango'],
            ['departamento_id' => 14, 'nombre' =>'Patzité'],
            ['departamento_id' => 14, 'nombre' =>'San Antonio Ilotenango'],
            ['departamento_id' => 14, 'nombre' =>'San Pedro Jocopilas'],
            ['departamento_id' => 14, 'nombre' =>'Cunén'],
            ['departamento_id' => 14, 'nombre' =>'San Juan Cotzal'],
            ['departamento_id' => 14, 'nombre' =>'Joyabaj'],
            ['departamento_id' => 14, 'nombre' =>'Nebaj'],
            ['departamento_id' => 14, 'nombre' =>'San Andrés Sajcabajá'],
            ['departamento_id' => 14, 'nombre' =>'Uspantán'],
            ['departamento_id' => 14, 'nombre' =>'Sacapulas'],
            ['departamento_id' => 14, 'nombre' =>'San Bartolomé Jocotenango'],
            ['departamento_id' => 14, 'nombre' =>'Canillá'],
            ['departamento_id' => 14, 'nombre' =>'Chicamán'],
            ['departamento_id' => 14, 'nombre' =>'Playa Grande -Ixcán'],
            ['departamento_id' => 14, 'nombre' =>'Pachalum'],
            ['departamento_id' => 15, 'nombre' =>'Salamá'],
            ['departamento_id' => 15, 'nombre' =>'San Miguel Chicaj'],
            ['departamento_id' => 15, 'nombre' =>'Rabinal'],
            ['departamento_id' => 15, 'nombre' =>'Cubulco'],
            ['departamento_id' => 15, 'nombre' =>'Granados'],
            ['departamento_id' => 15, 'nombre' =>'El Chol'],
            ['departamento_id' => 15, 'nombre' =>'San Jerónimo'],
            ['departamento_id' => 15, 'nombre' =>'Purulhá'],
            ['departamento_id' => 16, 'nombre' =>'Cobán'],
            ['departamento_id' => 16, 'nombre' =>'Santa Cruz Verapaz'],
            ['departamento_id' => 16, 'nombre' =>'San Cristóbal Verapaz'],
            ['departamento_id' => 16, 'nombre' =>'Tactic'],
            ['departamento_id' => 16, 'nombre' =>'Tamahú'],
            ['departamento_id' => 16, 'nombre' =>'Tucurú'],
            ['departamento_id' => 16, 'nombre' =>'Panzós'],
            ['departamento_id' => 16, 'nombre' =>'Senahú'],
            ['departamento_id' => 16, 'nombre' =>'San Pedro Carchá'],
            ['departamento_id' => 16, 'nombre' =>'San Juan Chamelco'],
            ['departamento_id' => 16, 'nombre' =>'Lanquín'],
            ['departamento_id' => 16, 'nombre' =>'Cahabón'],
            ['departamento_id' => 16, 'nombre' =>'Chisec'],
            ['departamento_id' => 16, 'nombre' =>'Chahal'],
            ['departamento_id' => 16, 'nombre' =>'Fray Bartolomé de las Casas'],
            ['departamento_id' => 16, 'nombre' =>'La Tinta'],
            ['departamento_id' => 17, 'nombre' =>'Flores'],
            ['departamento_id' => 17, 'nombre' =>'San José'],
            ['departamento_id' => 17, 'nombre' =>'San Benito'],
            ['departamento_id' => 17, 'nombre' =>'San Andrés'],
            ['departamento_id' => 17, 'nombre' =>'La Libertad'],
            ['departamento_id' => 17, 'nombre' =>'San Francisco'],
            ['departamento_id' => 17, 'nombre' =>'Santa Ana'],
            ['departamento_id' => 17, 'nombre' =>'Dolores'],
            ['departamento_id' => 17, 'nombre' =>'San Luis'],
            ['departamento_id' => 17, 'nombre' =>'Sayaxché'],
            ['departamento_id' => 17, 'nombre' =>'Melchor de Mencos'],
            ['departamento_id' => 17, 'nombre' =>'Poptún'],
            ['departamento_id' => 18, 'nombre' =>'Puerto Barrios'],
            ['departamento_id' => 18, 'nombre' =>'Livingston'],
            ['departamento_id' => 18, 'nombre' =>'El Estor'],
            ['departamento_id' => 18, 'nombre' =>'Morales'],
            ['departamento_id' => 18, 'nombre' =>'Los Amates'],
            ['departamento_id' => 19, 'nombre' =>'Zacapa'],
            ['departamento_id' => 19, 'nombre' =>'Estanzuela'],
            ['departamento_id' => 19, 'nombre' =>'Río Hondo'],
            ['departamento_id' => 19, 'nombre' =>'Gualán'],
            ['departamento_id' => 19, 'nombre' =>'Teculután'],
            ['departamento_id' => 19, 'nombre' =>'Usumatlán'],
            ['departamento_id' => 19, 'nombre' =>'Cabañas'],
            ['departamento_id' => 19, 'nombre' =>'San Diego'],
            ['departamento_id' => 19, 'nombre' =>'La Unión'],
            ['departamento_id' => 19, 'nombre' =>'Huité'],
            ['departamento_id' => 20, 'nombre' =>'Chiquimula'],
            ['departamento_id' => 20, 'nombre' =>'San José La Arada'],
            ['departamento_id' => 20, 'nombre' =>'San Juan Ermita'],
            ['departamento_id' => 20, 'nombre' =>'Jocotán'],
            ['departamento_id' => 20, 'nombre' =>'Camotán'],
            ['departamento_id' => 20, 'nombre' =>'Olopa'],
            ['departamento_id' => 20, 'nombre' =>'Esquipulas'],
            ['departamento_id' => 20, 'nombre' =>'Concepción Las Minas'],
            ['departamento_id' => 20, 'nombre' =>'Quetzaltepeque'],
            ['departamento_id' => 20, 'nombre' =>'San Jacinto'],
            ['departamento_id' => 20, 'nombre' =>'Ipala'],
            ['departamento_id' => 21, 'nombre' =>'Jalapa'],
            ['departamento_id' => 21, 'nombre' =>'San Pedro Pinula'],
            ['departamento_id' => 21, 'nombre' =>'San Luis Jilotepeque'],
            ['departamento_id' => 21, 'nombre' =>'San Manuel Chaparrón'],
            ['departamento_id' => 21, 'nombre' =>'San Carlos Alzatate'],
            ['departamento_id' => 21, 'nombre' =>'Monjas'],
            ['departamento_id' => 21, 'nombre' =>'Mataquescuintla'],
            ['departamento_id' => 22, 'nombre' =>'Jutiapa'],
            ['departamento_id' => 22, 'nombre' =>'El Progreso'],
            ['departamento_id' => 22, 'nombre' =>'Santa Catarina Mita'],
            ['departamento_id' => 22, 'nombre' =>'Agua Blanca'],
            ['departamento_id' => 22, 'nombre' =>'Asunción Mita'],
            ['departamento_id' => 22, 'nombre' =>'Yupiltepeque'],
            ['departamento_id' => 22, 'nombre' =>'Atescatempa'],
            ['departamento_id' => 22, 'nombre' =>'Jerez'],
            ['departamento_id' => 22, 'nombre' =>'El Adelanto'],
            ['departamento_id' => 22, 'nombre' =>'Zapotitlán'],
            ['departamento_id' => 22, 'nombre' =>'Comapa'],
            ['departamento_id' => 22, 'nombre' =>'Jalpatagua'],
            ['departamento_id' => 22, 'nombre' =>'Conguaco'],
            ['departamento_id' => 22, 'nombre' =>'Moyuta'],
            ['departamento_id' => 22, 'nombre' =>'Pasaco'],
            ['departamento_id' => 22, 'nombre' =>'San José Acatempa'],
            ['departamento_id' => 22, 'nombre' =>'Quesada'],
        ];

        foreach($municipios as $municipio){
            Municipio::create($municipio);
        }
    }
}
